* libname master 'c:\Documents and Settings\epb4\Desktop';
libname master '/bbkinghome/sschaner/Angrist Work/Web Papers/Angristetal_2002/Bettinger/to simone/';

data temp;
	set master.aerdat4;
**PANEL A;
proc means n mean std n mean;
  var vouch0;
  where dbogota | djamundi;
proc means n mean std n mean;
  var vouch0;
  where dbogota=1 & d1995;
proc means n mean std n mean;
  var vouch0;
  where dbogota=1 & d1997;
proc means n mean std n mean;
  var vouch0;
  where djamundi;
**PANEL B;
proc means n mean std n mean;
  var vouch0 ;
    where (bog95asd | jam93asd | bog97asd);
proc means n mean std n mean;
  var vouch0 ;
  where  bog95asd ;
proc means n mean std n mean;
  var vouch0 ;
    where  bog97asd;
proc means n mean std n mean;
  var vouch0 ;
  where jam93asd;
proc means n mean std;
	var response;
	where (bog95asd | bog97asd | jam93asd);
proc means n mean std;
	var response;
	where (bog95asd | bog97asd | jam93asd) & vouch0;
proc means n mean std;
	var response;
	where (bog95asd | bog97asd | jam93asd) & vouch0=0;
proc means n mean std;
	var response;
	where bog95asd;
proc means n mean std;
	var response;
	where bog95asd & vouch0;
proc means n mean std;
	var response;
	where bog95asd & vouch0=0;
proc means n mean std;
	var response ;
	where bog97asd;
proc means n mean std;
	var response ;
	where bog97asd & vouch0;
proc means n mean std;
	var response ;
	where bog97asd & vouch0=0;
proc means n mean std;
	var response ;
	where jam93asd;
proc means n mean std;
	var response ;
	where jam93asd & vouch0;
proc means n mean std;
	var response ;
	where jam93asd & vouch0=0;

data temp; 
 set master.aerdat4;
 keep vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp;
**PANEL C;
proc means n mean std;
var vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp; 
where (bog95smp=1 | bog97smp=1 |jam93smp=1);

proc means n mean std;
 var vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp; 
 where bog95smp=1 ;

proc means n mean std;
 var vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp; 
 where bog97smp=1;

proc means n mean std;
 var vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp; 
 where jam93smp=1;

 * TEST TAKERS
data temp;
	set master.aerdat4;
	if test_tak=1;
run;
 	**COLUMN 5;
proc means n mean std;
 var vouch0 age2 sex age hsvisit prscha_1 prscha_2 prsch_c scyfnsh inschl bog95smp bog97smp jam93smp; 
run;
run;
